# Generated by Django 5.0.3 on 2024-03-15 08:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hospital", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointment",
            name="doctor",
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="patient",
        ),
        migrations.AddField(
            model_name="patient",
            name="age",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="email",
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AddField(
            model_name="patient",
            name="fee",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="treatment",
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="patient",
            name="gender",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterModelTable(
            name="patient",
            table="patient",
        ),
        migrations.DeleteModel(
            name="Doctor",
        ),
        migrations.DeleteModel(
            name="Appointment",
        ),
    ]
