# Generated by Django 5.0.3 on 2024-03-15 12:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "hospital",
            "0002_remove_appointment_doctor_remove_appointment_patient_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Login",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("password", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "login",
            },
        ),
    ]
